name: Build site
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Dependencies
        run: |
          sudo apt update
          sudo apt install -y curl python3.9 python3-pip
          curl -LSso pandoc-amd64.deb https://github.com/jgm/pandoc/releases/download/3.1.9/pandoc-3.1.9-1-amd64.deb
          sudo dpkg -i pandoc-amd64.deb
          sudo npm install -g mermaid-filter
      - name: Build
        run: |
          python3.9 -m venv venv
          source venv/bin/activate
          pip install pyyaml
          MODE=build python w.py
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./_site
          github_token: ${{ secrets.GITHUB_TOKEN }}
