jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@master
    - name: Build
      run: npm install && npm run build
    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: _site
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
